accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "WTFPL",
    "CC0-1.0",
    "Artistic-2.0",
    "ISC"
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
