accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "WTFPL",
    "CC0-1.0",
    "Artistic-2.0",
    "ISC",
    "Zlib",
    "BSL-1.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "BSD-2-Clause",
    "CDLA-Permissive-2.0"
]

ignore-build-dependencies = true
ignore-dev-dependencies = true

targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc"
]
