[package]
name = "cloggen"
version = "1.0.1"
edition = "2021"

[dependencies]
tectonic = {version = "0.15.0", features=["external-harfbuzz"]}
clap = { version = "4.5.20", features = ["derive"] }
encoding_rs = "0.8.35"
serde_json = "1.0.132"
csv = "1.3.0"
rand = "0.8.5"


[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "4a600e9fea71bd7872080cbb716797e04d30e6d3"
overlay-triplets-path = "dist/vcpkg-triplets"

[package.metadata.vcpkg.target]
x86_64-apple-darwin = { install = ["freetype", "harfbuzz[graphite2]", "icu"] }
aarch64-apple-darwin = { triplet = "arm64-osx", install = [
    "freetype",
    "harfbuzz[graphite2]",
    "icu",
] }
x86_64-unknown-linux-gnu = { install = [
    "fontconfig",
    "freetype",
    "harfbuzz[graphite2]",
    "icu",
] }
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-release", install = [
    "fontconfig",
    "freetype",
    "harfbuzz[graphite2]",
    "icu",
] }
