name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: vcpkg
      run: |
        vcpkg install fontconfig freetype "harfbuzz[graphite2]" icu
    
