name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    env:
      TECTONIC_DEP_BACKEND: vcpkg
      RUSTFLAGS: -Ctarget-feature=+crt-static
      VCPKGRS_TRIPLET: x64-windows-static-release
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1.4.1

    - name: Tectonic's vcpkg dependencies
      run: |
        vcpkg integrate install
        vcpkg install fontconfig freetype "harfbuzz[graphite2]" icu graphite2

    - name: Build
      run: |
        cargo build --release
